import type { Metadata } from "next";
import "@/shared/ui/globals.css";
import { TelegramProvider } from "@/shared/providers/TelegramProvider";
import { ThemeProvider } from "@/shared/providers/ThemeProvider";
import { AuthProxy } from "@/shared/providers/AuthProxy";
import { ErudaDevTools } from "@/shared/providers/ErudaDevTools";
import { SidebarProvider, SidebarTrigger } from "@/shared/ui/components/ui/sidebar";
import { AppSidebar } from "@/shared/ui/components/app-sidebar";

export const metadata: Metadata = {
  title: "app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        {process.env.NODE_ENV === 'development' ? <ErudaDevTools /> : null}
        <TelegramProvider>
          <ThemeProvider>
            <AuthProxy>
              <SidebarProvider>
                <AppSidebar />
                <main className="flex-1">
                  <div className="p-2">
                    <SidebarTrigger />
                  </div>
                  {children}
                </main>
              </SidebarProvider>
            </AuthProxy>
          </ThemeProvider>
        </TelegramProvider>
      </body>
    </html>
  );
}
