import type { Metadata } from "next";
import "@/shared/ui/globals.css";
import { Providers } from "@/shared/providers/Providers";

export const metadata: Metadata = {
  title: "app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
